// pages/cart.js
import useCartStore from "../store/cartStore";
import css from "../styles/Cart.module.css";
import Head from "next/head";
import Layout from "../components/Layout";
import Image from "next/image";
import toast from "react-hot-toast";

export default function Cart() {
  const cartItems = useCartStore((state) => state.cartItems);
  const removeFromCart = useCartStore((state) => state.removeFromCart);

  function handleRemoveFromCart(index) {
    const removedItem = cartItems[index];
    removeFromCart(index);

    toast.success(`${removedItem.name} removed from the cart!`);
  }
  const totalItems = cartItems.reduce(
    (total, item) => total + item.quantity,
    0
  );
  const totalPrice = cartItems.reduce(
    (total, item) => total + item.price * item.quantity,
    0
  );

  return (
    <Layout>
      <Head>
        <title>Velvet Paws - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" href="/android-chrome-192x192.png" sizes="192x192" />
        <link rel="icon" href="/android-chrome-512x512.png" sizes="512x512" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
      </Head>
      <div className="grid grid-cols-1 mt-18 p-8 text-xs gap-0 lg:grid-cols-3 lg:text-base lg:gap-10 mt-16 lg:mt-28">
        <h2 className="font-bold text-4xl text-base-sub-title text-center mb-6 mt-12 lg:hidden">
          Our Product
        </h2>
        <div className={css.detail}>
          {cartItems.length === 0 ? (
            <p className="text-center font-bold text-lg ">Your cart is empty</p>
          ) : (
            <table className={css.table}>
              <thead>
                <th>Gambar</th>
                <th>Nama</th>
                <th>Kategori</th>
                <th>Harga</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
              </thead>
              <tbody className={css.tbody}>
                {cartItems.map((item, index) => (
                  <tr key={index}>
                    <td className={css.imageTd}>
                      <Image
                        objectFit="cover"
                        width={85}
                        height={85}
                        className="m-auto"
                        alt=""
                        src={item.image}
                      />
                    </td>
                    <td>{item.name}</td>
                    <td>{item.category}</td>
                    <td>{item.price}</td>
                    <td>{item.quantity}</td>
                    <td>{item.quantity * item.price}</td>
                    <td
                      style={{
                        color: "red",
                        cursor: "pointer",
                        fontWeight: "bold",
                      }}
                      onClick={() => {
                        handleRemoveFromCart(index);
                      }}
                    >
                      X
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
        <div className={css.cart}>
          <span>Cart</span>
          <div className={css.CartDetails}>
            <div>
              <span>Items</span>
              <span>{totalItems}</span>
            </div>
            <div>
              <span>Total</span>
              <span>{totalPrice}</span>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
